name: Deploy React App to AWS Lightsail

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # Step 3: Install dependencies and build the project
      - name: Install Dependencies and Build
        env: # Inject environment variables from GitHub Secrets
          VITE_APP_AWS_API_URL: ${{ secrets.VITE_APP_AWS_API_URL }}
          VITE_API_KEY: ${{ secrets.VITE_API_KEY }}
        run: |
          npm ci
          npm run build

      # Step 4: Rename the build output directory (if required)
      - name: Rename dist to bethel-frontend
        run: mv ./dist ./bethel-frontend

      # Step 5: Clean up temporary deployment directory on Lightsail
      - name: Clean Temporary Directory on Lightsail
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ${{ secrets.LIGHTSAIL_USER }}
          key: ${{ secrets.LIGHTSAIL_KEY }}
          script: |
            # Remove old temporary directory if it exists
            rm -rf ~/deploy-temp
            mkdir ~/deploy-temp

      # Step 6: Copy files to Lightsail
      - name: Copy Files to Lightsail
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ${{ secrets.LIGHTSAIL_USER }}
          key: ${{ secrets.LIGHTSAIL_KEY }}
          source: ./bethel-frontend/
          target: ~/deploy-temp/

      # Step 7: Deploy and configure on Lightsail
      - name: Deploy on Lightsail
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ${{ secrets.LIGHTSAIL_USER }}
          key: ${{ secrets.LIGHTSAIL_KEY }}
          script: |
            # Remove old deployment
            sudo rm -rf /var/www/html/bethel-frontend

            # Move new files to the deployment directory
            sudo mv ~/deploy-temp/* /var/www/html/

            # Remove temporary deployment folder
            sudo rm -rf ~/deploy-temp

            # Clear any server-side cache
            sudo rm -rf /var/cache/nginx/*

            # Restart NGINX to apply changes
            sudo systemctl restart nginx
