name: Deploy React (Vite) to Firebase Hosting

on:
  push:
    branches:
      - firebase

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout repo
      - name: Checkout
        uses: actions/checkout@v3

      # 2️⃣ Setup Node.js 20+
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm install

      # 4️⃣ Build React app (Vite)
      - name: Build React app
        run: npm run build
        env:
          VITE_APP_API_URL: ${{ secrets.VITE_APP_API_URL }}
          VITE_API_KEY: ${{ secrets.VITE_API_KEY }}

      # 5️⃣ Verify dist folder (optional)
      - name: Verify dist folder
        run: ls -la dist

      # 6️⃣ Deploy to Firebase Hosting
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          channelId: live
          projectId: bethel-1e8fc
          firebaseToolsVersion: latest
          entryPoint: .
